title: Hello! I'm sudoku.huang
description: > # this means to ignore newlines until "baseurl:"
    Focos on C/C++.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: sudoku.huang # add your name
author-img: sudoku.jpg # add your photo
about-author: 懦怯囚禁人的灵魂，希望可以感受自由。强者自救，圣者渡人。 # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: sudokuhk # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: hk2305621@126.com  # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
